# generated by datamodel-codegen:
#   filename:  cacheinfo.json
#   timestamp: 2025-05-26T09:55:06+00:00

from __future__ import annotations
from pydantic import BaseModel


class CacheInfo(BaseModel):
    usage: int
